name: Angular Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Saca el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Instala Node.js 20.x y cachea npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3) Instala dependencias y build de Angular en /docs
      - name: Install & build Angular
        run: |
          npm ci
          npm run build -- --configuration production --output-path docs --base-href=/

      # 4) Login en Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5) Construye y sube la imagen usando el Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/mycv:latest
